<a href="https://colab.research.google.com/github/axbuild/ds/blob/master/sf_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = pd.Series(["Январь", "Февраль", "Март", "Апрель"],
            index = ['Первый', "Второй", "Третий", "Четвёртый"])
print(data)
print(data.loc[["Первый", "Третий"]])

Первый        Январь
Второй       Февраль
Третий          Март
Четвёртый     Апрель
dtype: object
Первый    Январь
Третий      Март
dtype: object


In [ ]:
import pandas as pd

s = pd.Series(["Ivanov", "Moscow"], index=["name", "city"])
print("name" in s)     # True, такой ключ есть
print("Ivanov" in s)    # False, такого ключа нет, это значение

True
False


In [ ]:
import pandas as pd

s = pd.Series(["Bo", "Ba"], index=["name", "city"])

def extract_values(row, keys):
  return row[keys].tolist()

extract_values(s, ["city"])

['Ba']

In [ ]:
import pandas as pd

s = pd.Series(["Bo", "Ba"], index=["name", "city"])

def extract_values_by_idx(row, idxs):
  return row.iloc[idxs].tolist()

extract_values_by_idx(s, [1])

['Ba']

In [ ]:
import pandas as pd

s = pd.Series(["Abc", "Def"], index=["name", "city"])

def get_or_default(row, key, default):
  return row[key] if key in row else default

get_or_default(s, "salary", 50)
get_or_default(s, "city", "Mos")

'Def'

In [ ]:
data = pd.DataFrame([['Иванов', 100, 'Сочи'], ['Петров', 200, 'Москва']])
print(data)

        0    1       2
0  Иванов  100    Сочи
1  Петров  200  Москва


In [ ]:
!curl "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html" > data.xlsx

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34627    0 34627    0     0  48770      0 --:--:-- --:--:-- --:--:-- 48770


In [ ]:
import pandas as pd
data = pd.read_excel('data.xlsx')
print(data)
data = pd.read_csv('people.csv', names=['Фамилия', 'Зарплата', 'Город'])
print(data)
print(data.head())
print(data.tail(1))

Давайте создадим таблицу со случайными данными: первый столбец будет иметь равномерное распределение на отрезке [0, 1], а второй - нормальное распределение с параметрами (mu=3, sigma=2):

In [ ]:
import random as random
import pandas as pd

data = [[random.random(), random.gauss(3, 2)] for _ in range(10000)]
data = pd.DataFrame(data, columns=['uniform', 'gauss_3_2'])
print(data.head())
print(data.info())
print(data.describe())

    uniform  gauss_3_2
0  0.519841   3.550109
1  0.566451   2.376845
2  0.802302   3.769845
3  0.865021   3.315956
4  0.870498   4.788750
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   uniform    10000 non-null  float64
 1   gauss_3_2  10000 non-null  float64
dtypes: float64(2)
memory usage: 156.4 KB
None
            uniform     gauss_3_2
count  10000.000000  10000.000000
mean       0.495432      2.985961
std        0.288179      2.001156
min        0.000237     -4.245815
25%        0.247035      1.645766
50%        0.494388      2.949255
75%        0.742474      4.306669
max        0.999724     10.697065


In [ ]:
import pandas as pd
import random as random

def random_table(a, b, n):
  data = [[random.uniform(a,b)] for x in range(n)]
  df = pd.DataFrame(data, columns=['uniform'])
  return df


random_table(5,10,10)

uniform
0  9.390034
1  9.308216
2  5.236293
3  6.537743
4  6.238053
5  6.234465
6  7.647763
7  6.460532
8  9.728975
9  9.158058

In [ ]:
import pandas as pd

def word_count(word):
  data = pd.read_csv('data/war_peace_processed.txt')
  words = data['1'].value_counts()
  return words[word]

word_count('что')

5097

In [ ]:
import pandas as pd

def word_with_count(count):
  data = pd.read_csv('data/war_peace_processed.txt')
  words = data['1'].value_counts()
  return words[words==count].keys()[0]

word_with_count(5097)

'что'

In [ ]:
import requests
import pandas as pd

data = pd.read_csv('titanic.csv')
#print(data.describe())
print(data["Survived"].mean())
print(data.groupby('Sex')["Survived"].mean())
print(data.groupby(['Sex', 'Class'])["Survived"].mean())
print(data.groupby(['Sex', 'Class'])["Age"].median())
obj = data.groupby(['Class', 'Survived'])["Age"].quantile(0.9)
print(obj[2.0, 1.0])   # здесь 2.0 - класс, а 1.0 - признак того, что пассажир выжил

0.3838383838383838
Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64
Sex     Class
female  1.0      0.968421
        2.0      0.920000
        3.0      0.496503
male    1.0      0.368852
        2.0      0.158879
        3.0      0.135447
Name: Survived, dtype: float64
Sex     Class
female  1.0      36.0
        2.0      28.0
        3.0      22.0
male    1.0      41.5
        2.0      30.0
        3.0      25.0
Name: Age, dtype: float64
44.70000000000002


In [ ]:
import pandas as pd

data_1 = pd.DataFrame([['Москва', 'Хвойный', 314],['Москва', 'Хвойный', 271], ['Москва', 'Лиственный', 567]], columns=['city', 'type', 'price'])

def avg_price(data, city, type):
  return data.groupby(['city','type'])['price'].mean()[city][type]

avg_price(data_1,'Москва','Хвойный')

292.5

In [ ]:
import pandas as pd

data_1 = pd.DataFrame([['Москва', 'Хвойный', 314],['Москва', 'Хвойный', 271], ['Москва', 'Лиственный', 567]], columns=['city', 'type', 'price'])

def max_city(data):
  return data.loc[data['price'].idxmax()]['city']

max_city(data_1)

'Москва'

In [ ]:
#8.1
import pandas as pd

data_1 = pd.DataFrame([['Москва', 'Хвойный', 314],\
                       ['Москва', 'Хвойный', 271],\
                       ['Балашиха', 'Лиственный', 567]],\
                       columns=['city', 'type', 'price'])

def good_cities(data, min_price):
  mean_cities = data.groupby(['city']).mean()
  return mean_cities[mean_cities['price']>=min_price]['price'].keys().tolist() #mean_cities.loc[mean_cities]
  #return data[data['price']>=min_price]['city'].tolist()

good_cities(data_1, 500)




['Балашиха']

In [ ]:
#8.2
import pandas as pd

data_1 = pd.DataFrame([['Москва', 'Хвойный', 314],\
                     ['Москва', 'Хвойный', 271],\
                     ['Москва', 'Лиственный', 1024],\
                     ['Балашиха', 'Лиственный', 567]],\
                     columns=['city', 'type', 'price'])

def best_price_with_fixed_type(data, type):
  mean_cities = data[data['type']==type].groupby(['city'])['price'].mean()
  return mean_cities.max()
  #return max(data[data['type']==type]['price'].tolist())

best_price_with_fixed_type(data_1, 'Лиственный')

1024

In [ ]:
#print(data.groupby(['Class'])['Survived'].mean().mul(100))
#print(data.groupby(['Class'])['Survived'].mean() * 100)

In [ ]:
#9.1
import pandas as pd

data = pd.DataFrame([[10, 20, 30],\
                     [5, 15, 35]],\
                     columns=['United Laplandia',\
                              'Honest Laplandia',\
                              'Laplandia for life'])
def win(data, party, voices):
  data[party]+=voices
  return data

win(data, 'United Laplandia', 50)


United Laplandia  Honest Laplandia  Laplandia for life
0                60                20                  30
1                55                15                  35

In [ ]:
import pandas as pd

data = pd.read_csv('titanic.csv')

result = data[['PassengerId','Survived']]
result = data.loc[[1,5],['PassengerId','Survived']]
result = data.loc[1:5,['PassengerId','Survived']]
result = data.iloc[1:5]
result = data.shape
print(result)

filtered = data.filter(items=['Age', 'Class', 'Survived'], axis=1)
print(filtered.info())
print(filtered)


(1309, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1046 non-null   float64
 1   Class     1304 non-null   float64
 2   Survived  891 non-null    float64
dtypes: float64(3)
memory usage: 30.8 KB
None
       Age  Class  Survived
0     22.0    3.0       0.0
1     38.0    1.0       1.0
2     26.0    3.0       1.0
3     35.0    1.0       1.0
4     35.0    3.0       0.0
...    ...    ...       ...
1304   NaN    3.0       NaN
1305  39.0    1.0       NaN
1306  38.5    3.0       NaN
1307   NaN    3.0       NaN
1308   NaN    3.0       NaN

[1309 rows x 3 columns]


In [ ]:
import pandas as pd

data_1 = pd.DataFrame([[10, 20, 30],\
                     [5, 15, 35]],\
                     index=['UIK128', 'UIK256'],\
                     columns=['United Laplandia', 'Honest Laplandia', 'Laplandia for life'])

def extract_item(data, row, col):
  return data.loc[row,[col]].tolist()[0]

extract_item(data_1, 'UIK256', 'United Laplandia')

5

In [ ]:
import pandas as pd

data = pd.read_csv('titanic.csv')

filtered = data.filter(items=['Age', 'Class', 'Survived'], axis=1)
print(filtered.corr())

               Age     Class  Survived
Age       1.000000 -0.406132 -0.077221
Class    -0.406132  1.000000 -0.341829
Survived -0.077221 -0.341829  1.000000


In [ ]:
#12.1
import pandas as pd

t1 = pd.DataFrame([['Moscow', 20],['Perm', 25]],\
                 columns=['city', 'temp'])
t2 = pd.DataFrame([['Moscow', 763],['Perm', 759]],\
                 columns=['city', 'pressure'])

def merge_weather(temp, pressure):
  return pd.merge(temp, pressure, on='city')

merge_weather(t1, t2) 

city  temp  pressure
0  Moscow    20       763
1    Perm    25       759

In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4])

print(type(arr1))
print(arr1)

arr2 = np.array([5,6,7,8], dtype=float)

print(arr2.dtype)

arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.shape(arr3))
print(arr3.shape)

arr4 = np.array([[[1, 2, 3], [3, 4, 5]]])

print(arr4.shape)
print(arr4)


print( np.empty(5) ) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

print( np.zeros((10, 7)) ) # массив размером 10x7, заполненный нулями 

print( np.ones((3,3,3)) ) # массив размером 3х3х3, заполненный единицами 

print( np.eye(3) ) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

print( np.full((3, 5), 3.14) )  # массив 3x5 заполненный числом 3.14

print( np.arange(0, 21, 7) )  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

print( np.linspace(0, 1, 5) )  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

print( np.random.rand(3, 3) )  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 1

print( np.random.randn(3, 3) )  # массив размера 3х3, заполненный случайными числами из стандартного нормального распределения

print( np.random.randint(0, 10, (3, 3)) )  # массив размера 3х3, заполненный случайными целыми числами из диапазона от 0 до 9 (включительно)

<class 'numpy.ndarray'>
[1 2 3 4]
float64
(3, 3)
(3, 3)
(1, 2, 3)
[[[1 2 3]
  [3 4 5]]]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  7 14]
[0.   0.25 0.5  0.75 1.  ]
[[0.0491858  0.66209185 0.39720553]
 [0.72307524 0.99534608 0.49564629]
 [0.92776395 0.43254072 0.27867077]]
[[ 9.78975103e-01  7.13382147e-01 -1.05666168e-03]
 [ 8.75016768e-01  5.74991516e-01 -2.01841306e+00]
 [ 1.80946468e-01  2.32406826e-01  9.29104215e-01]]
[[0 1 3]
 [5 2 8]
 [7 4 4]]


In [ ]:
import numpy as np

m = np.eye(10)

print(m)
print(m[2,3])

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
0.0


In [ ]:
import numpy as np

m = np.zeros((3, 5))

print(m)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
np.array([x for x in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_array[5]

5

In [ ]:
my_array[-1]

9

In [ ]:
my_array[3:6]

array([3, 4, 5])

In [ ]:
my_array[1:8:3]

array([1, 4, 7])

In [ ]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
print(my_array)
print(my_array[1][2])
print(my_array[1,2])
print(my_array[1])
print(my_array[:,2])
print(my_array[1:, 1:3])

[[ 1  2  3  4]
 [10 11 12 13]
 [45 46 47 48]]
12
12
[10 11 12 13]
[ 3 12 47]
[[11 12]
 [46 47]]


In [ ]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array
my_slice = my_array[1:3, 2:4]
my_slice
my_slice[:] = 0
my_array

array([[52, 23, 15, 39, 66, 47],
       [83, 34,  0,  0, 36, 26],
       [68, 41,  0,  0, 37, 19],
       [95, 46, 86, 48, 95, 18]])

In [ ]:
import numpy as np

data_1 = np.random.randint(1, 100, (4, 6)) 

def extract_even(data):
  return data[::2]


extract_even(data_1)


array([[72, 29, 45, 13, 39, 17],
       [11, 91, 19, 82, 59, 43]])

In [ ]:
#19.2
import numpy as np

data_1 = np.array([[-0.64025045, -0.76642206],\
       [ 0.49964569,  1.14386726],\
       [ 0.781745  ,  0.31180694],\
       [ 0.66771689, -0.80851581]])

def extract_column(data, bad_column):
  return data[:,bad_column]

extract_column(data_1, 1)

array([-0.76642206,  1.14386726,  0.31180694, -0.80851581])

In [ ]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'\
      .format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [ ]:
import numpy as np

def normal(n, mu, sigma):
  return np.random.normal(mu, sigma, n)

normal(3,3,2)

array([3.99804982, 4.52598628, 4.79243906])

In [ ]:
import numpy as np

data_1 = np.array([[9, 6, 1],\
                  [6, 0, 7],\
                  [3, 2, 4]])

def win(data, column, value):
  #t = np.full((data.shape[1], 1), value)
  data[:,column]+=value
  return  data #data.shape[0] #data[:,column]

win(data_1, 0, 5)

array([[14,  6,  1],
       [11,  0,  7],
       [ 8,  2,  4]])

In [ ]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5)) #превратит исходный одномерный массив в двумерный массив (матрицу), содержащий 4 строки и 5 столбцов

array([[5, 0, 6, 4, 5],
       [0, 2, 2, 0, 2],
       [0, 9, 9, 8, 8],
       [7, 6, 0, 1, 3]])

In [ ]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [ ]:
#np.array([1, 2, 3, 4, 5]).reshape((2, 3))
#np.array([1, 2, 3, 4, 5, 6]).reshape((2, 3)).T

In [ ]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[3, 4, 3, 3],
       [7, 7, 7, 7],
       [8, 7, 1, 3]])

In [ ]:
my_array<5

array([[False,  True,  True, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
my_array[my_array<5]

array([3, 1, 1, 4, 2, 3, 1])

In [ ]:
mask = np.array([1, 0, 1, 0], dtype=bool)
print(my_array)
my_array[:, mask]
print(mask)
print(my_array)

[[3 4 3 3]
 [7 7 7 7]
 [8 7 1 3]]
[ True False  True False]
[[3 4 3 3]
 [7 7 7 7]
 [8 7 1 3]]


In [ ]:
#Как найти маску столбцов с суммой, большей 15?
#np.sum(a, axis = 0) > 15 верно
#Как оставить в матрице столбцы с суммой, большей 15?
#a[:,np.sum(a, axis = 0) > 15]

In [ ]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[0, 5, 6, 8, 4, 3],
       [1, 9, 0, 2, 0, 8],
       [7, 1, 7, 2, 7, 4],
       [7, 8, 0, 8, 4, 5]])

In [ ]:
np.sort(my_array, axis=1)

array([[0, 3, 4, 5, 6, 8],
       [0, 0, 1, 2, 8, 9],
       [1, 2, 4, 7, 7, 7],
       [0, 4, 5, 7, 8, 8]])

In [ ]:
np.sort(my_array, axis=0)

array([[0, 1, 0, 2, 0, 3],
       [1, 5, 0, 2, 4, 4],
       [7, 8, 6, 8, 4, 5],
       [7, 9, 7, 8, 7, 8]])

In [36]:
import numpy as np

def survive_or_not(x, p, q):
    prob_life = 0.7
    prob_array = np.full((1, len(x)), prob_life)
    i_age = np.where(x[:,0] > 60)
    i_price = np.where(x[:,1] < 50)
    prob_array[0,i_age] *=p
    prob_array[0,i_price] *=q
    return np.random.binomial(1, prob_array)

survive_or_not(np.array([[30, 250],[75, 20]]), 0.5, 0.5)
#np.zeros((2,))
#np.random.binomial(1, np.array([[0.7, 0.6]]))

array([[0, 0]])

In [38]:
import numpy as np

def classification_loss(predictions, answers):
    return ((-(np.log(predictions) * answers +\
               np.log(1-predictions) * (1-answers))).mean())

classification_loss(np.array([0.2, 0.2]), np.array([1, 0]))

0.916290731874155