# Линейный оператор

Умножение матрицы на вектор можно представить как его одновременный поворот и растяжение.

А если рассмотреть умножение матрицы на все векторы пространства, то получится преобразование всего этого пространства или так называемый линейный оператор.

*** Как действует матрина на вектор ***




In [1]:
import numpy as np 

A = np.matrix("0,2;5,0")
x = np.matrix("3;4")

A*x


matrix([[ 8],
        [15]])

In [2]:
F = np.matrix("1,0,0;0,0,1;0,-1,0")
v = np.matrix("1;2;3")
F*v

matrix([[ 1],
        [ 3],
        [-2]])

In [4]:
F = np.matrix("2,1;1,2")
u = np.matrix("1;-1")
v = np.matrix("1;1")

Fu = F*u 
Fv = F*v
print(Fu,Fv)

[[ 1]
 [-1]] [[3]
 [3]]
