# Неоднородные СЛАУ 
## по методу наименьших квадратов (Ordinary Least Squares, OLS)

* алгоритм — решение неоднородных систем линейных алгебраических уравнений или СЛАУ;
* контекст задачи прогнозирования.

*** В решении СЛАУ возможно 3 случая: ***

* «Идеальная пара»
Это так называемые определённые системы, имеющие единственное решение.
* «В активном поиске»
Недоопределённые системы, в которых решений бесконечно много.
* «Всё сложно»
Это переопределённые системы, в которых решений нет вовсе

<a href="http://mathprofi.ru/metod_gaussa_dlya_chainikov.html">Link</a>
<a href="http://www.machinelearning.ru/wiki/index.php?title=%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D0%B5%D1%80%D0%B5%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B9_%D0%A1%D0%9B%D0%90%D0%A3">Link</a>
<a href="https://xn--80ahcjeib4ac4d.xn--p1ai/information/solving_systems_of_linear_equations_in_python/">Link</a>
<a href="https://stackabuse.com/solving-systems-of-linear-equations-with-pythons-numpy/">Link</a>

In [7]:
import numpy as np 

A = np.matrix("1,1;1,2")
b = np.matrix("1,2")

A-b 

matrix([[ 0, -1],
        [ 0,  0]])

In [82]:
import numpy as np 

m = np.matrix("1,1;1,2;1,1")
res = np.matrix("1;2;12")
w = np.matrix("11;-4.5")

np.linalg.inv(m.T*m) * (m.T*m)*w


matrix([[11. ],
        [-4.5]])

In [87]:
#6.1
import numpy as np 

A = np.matrix("1,-5;2,1;1,1")
b = np.matrix("1;2;2")
w = np.matrix("1;1")

b_p = A*w
e = b - b_p
e

matrix([[ 5],
        [-1],
        [ 0]])

In [89]:
#2.6.3

A = np.matrix("1,2;-3,1;1,2;1,-1")
b = np.matrix("1;4;5;0")

w = np.linalg.inv(A.T*A) * A.T*b

matrix([[-0.5],
        [ 1.6]])

In [91]:
A.T*A
np.linalg.inv(A.T*A)

matrix([[0.08333333, 0.        ],
        [0.        , 0.1       ]])

In [92]:
A.T*b

matrix([[-6],
        [16]])

In [2]:
CRIM=0.2
RM=6
y = -29.3-0.26*CRIM+8.4*RM
y

21.048000000000005

In [3]:
(11+8)/2

9.5

In [28]:
import numpy as np 
import math 

x1 = np.matrix("11;8")
x1_mean = np.mean(x1)

print(x1_mean)

x1_center = x1-np.matrix("9.5;9.5")
x1_center

9.5


matrix([[ 1.5],
        [-1.5]])

In [21]:
x1_center_norm = math.sqrt(1.5**2+(-1.5)**2)
x1_center_norm


2.1213203435596424

In [20]:
x1_st = 1/x1_center_norm*x1_center
x1_st

matrix([[ 0.70710678],
        [-0.70710678]])