In [2]:
import numpy as np 
s=np.array([33,65,50,45])
print(s, s[2], len(s))

[33 65 50 45] 50 4


In [3]:
x = np.array([59.50, 31.40, 19, 2, 60550, 2])
# В NumPy вектор и массив - одно и то же. 
# Исключение - понятие вектор-столбец и вектор-строка - фактически двумерные массивы, 
# где один из атрибутов shape равен 1.

print("ndim:", x.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", x.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


In [4]:
# вычислим долю жилой площади в квартире
share_living_space = x[1]/x[0]

In [5]:
#удаление признаков по индексу
x = np.delete(x, [0, 1])

In [6]:
#вставка признаков по индексу
x = np.append(x, share_living_space)

There are e and c are collinear: $ \vec{e}  ||  \vec{c} $

In [14]:
#арифметические операции
a = np.array([10,8,5,1])
b = np.array([5,15,9,7])
c=a+b
d=a-b
e=c*0.2
print(c)
print(d)
#коллинеарные вектора
print(e)

[15 23 14  8]
[ 5 -7 -4 -6]
[3.  4.6 2.8 1.6]


### Сложение векторов и умножение на число: особые случаи
* Сложение противоположенных векторов равно 0
* Умножение ветора на 0 равно 0
* Умножение на нулевой вектор равно 0


In [24]:
air = np.array([120000,150000,90000], dtype='f')
wir = np.array([130000,130000,130000], dtype='f')
tie = np.array([2000,3000,2500], dtype='f')
tir = tie*72.0
print(tir)
print(air+wir+tir)


[144000. 216000. 180000.]
[394000. 496000. 400000.]
